server:
  port: 9999
  servlet:
    # ???????
    context-path: /warehouse

spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    password: 20001030
  # ??????
  datasource:
    url: jdbc:mysql://localhost:3306/db_warehouse?serverTimezone=UTC
    username: root
    password: 20001030
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ??????
    map-underscore-to-camel-case: true
  # ???????
  type-aliases-package: com.ian.pojo

# token ????
warehouse:
  expire-time: 360000000

file:
  # ????????
  upload-path: classpath:static/img/upload
  # ???????????????????
  access-path: /img/upload/

